version: "3.9"

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./apps/nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nextjs:/app
      # Prevent node_modules and .next from being overwritten
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_OPENWEATHER_API_KEY=ffe660efdd4b0b8382acfad056e03bb1
      - BETTER_AUTH_SECRET=bvvybf5oOio27DfGVxCnwqRjP2AvTZfM
      # - BETTER_AUTH_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongodb:27017/tugas_akhir
      - GOOGLE_CLIENT_ID=44801896856-qpud5qubmi3n4idhltf6crc8n4evfcsm.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    depends_on:
      - mongodb

  flask:
    build:
      # Specify our app directory as the context
      context: ./apps/flask
      # Use the Dockerfile that exists within the directory we specified above
      dockerfile: ./Dockerfile
    ports:
      # Flask server
      - "5000:5000"
      # Flask server debug port
      - "5678:5678"
    command: flask run --host=0.0.0.0 --port=5000
    # command: tail -f /dev/null
    volumes:
      - ./apps/flask/:/code
    environment:
      # Specify the path within our Docker container that contains our application code
      FLASK_APP: /code/app.py
      FLASK_ENV: development

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: tugas_akhir

volumes:
  mongo-data:
