version: "3.9"

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./apps/nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./apps/nextjs:/app
      # Prevent node_modules and .next from being overwritten
      - /app/node_modules
      - /app/.next
    env_file:
          - ./apps/nextjs/.env.local
    depends_on:
      - mongodb

  flask:
    build:
      # Specify our app directory as the context
      context: ./apps/flask
      # Use the Dockerfile that exists within the directory we specified above
      dockerfile: ./Dockerfile
    ports:
      # Flask server
      - "5000:5000"
      # Flask server debug port
      - "5678:5678"
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./apps/flask/:/code
    environment:
      # Specify the path within our Docker container that contains our application code
      FLASK_APP: /code/app.py
      FLASK_ENV: development

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: tugas_akhir

volumes:
  mongo-data:
